#syntax=docker/dockerfile:1

FROM node:18.17.1

WORKDIR /strathlostandfound/frontend

COPY . /strathlostandfound/frontend/

# Install dependencies
RUN npm install --force




EXPOSE 5173

CMD ["npm","run", "start:frontend", "--", "--host", "0.0.0.0"]

