services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000" 


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"

