services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "5000:5000" 


  frontend:
    build:
      context: .
      dockerfile: dockerfile.web
    ports:
      - "5173:5173"

